import { createSlice } from '@reduxjs/toolkit'

const initialState = {
    loading : false ,
    login : false ,
    username : null ,
}

const authSlice = createSlice({
    name : "auth", 
    initialState : initialState ,
    reducers : {

        setLoading(state, value){
            state.loading = value.payload ;
        } ,
        
        setLogin(state, value){
            state.login = value.payload ;
        } ,

        setUsername(state, value){
            state.username = value.payload ;
        }
    }
})

// ACTIONS =  Extract action creators from the slice
export const {setLoading,setLogin,setUsername } = authSlice.actions ;

// REDUCER =  Export the reducer function generated by createSlice
export default authSlice.reducer;

